### ISSUE TITLE
ImportError: cannot import name 'computed_field' from 'pydantic' 0.1.7 on mac

### ISSUE THREAD

**Issue by coleslaw481** [fairscape/fairscape-cli#22]
using python 3.8.2 on mac getting the following error with 0.1.7:

```
$ fairscape-cli rocrate
Traceback (most recent call last):
  File "/Users/churas/anaconda3/envs/python382/bin/fairscape-cli", line 5, in <module>
    from fairscape_cli.main import cli
  File "/Users/churas/anaconda3/envs/python382/lib/python3.8/site-packages/fairscape_cli/main.py", line 3, in <module>
    from fairscape_cli.validate import validate_json
  File "/Users/churas/anaconda3/envs/python382/lib/python3.8/site-packages/fairscape_cli/validate/validate_json.py", line 1, in <module>
    from fairscape_cli.models import (
  File "/Users/churas/anaconda3/envs/python382/lib/python3.8/site-packages/fairscape_cli/models/__init__.py", line 7, in <module>
    from fairscape_cli.models.rocrate import ROCrate
  File "/Users/churas/anaconda3/envs/python382/lib/python3.8/site-packages/fairscape_cli/models/rocrate.py", line 11, in <module>
    from pydantic import (
ImportError: cannot import name 'computed_field' from 'pydantic' (/Users/churas/anaconda3/envs/python382/lib/python3.8/site-packages/pydantic/__init__.cpython-38-darwin.so)
```

**Comment by mlev71** [comment]
Hi Chris this is an issue from migrating to pydantic v2.
