### ISSUE TITLE
fairscape-cli 0.1.5a4 register computation fails

### ISSUE THREAD

**Issue by coleslaw481** [fairscape/fairscape-cli#24]
python 3.8.2 fairscape-cli 0.1.5a4 failing on register computation

```
mkdir y
cd y
fairscape-cli rocrate init --name somenamehahahah --organization-name orgnameasdfasdfasdf --project-name projectnamehahah
fairscape-cli rocrate register computation --name 'name' --run-by 'runby' --date-created '08-03-2023' --command cmd --description desc --guid e3fa80d6-80b0-44cf-a6d7-6397cc3ef6bf --used-software 'ark:/s1' --used-dataset asdf --generated 'ark:/g1' `pwd`
```

**Outputs this:**

```
Computation Validation Error
1 validation error for Computation
description
  ensure this value has at least 10 characters (type=value_error.any_str.min_length; limit_value=10)
Traceback (most recent call last):
  File "/Users/churas/anaconda3/envs/python382/bin/fairscape-cli", line 8, in <module>
    sys.exit(cli())
  File "/Users/churas/anaconda3/envs/python382/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/churas/anaconda3/envs/python382/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/churas/anaconda3/envs/python382/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/churas/anaconda3/envs/python382/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/churas/anaconda3/envs/python382/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/churas/anaconda3/envs/python382/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/churas/anaconda3/envs/python382/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/churas/anaconda3/envs/python382/lib/python3.8/site-packages/fairscape_cli/rocrate/rocrate.py", line 357, in computation
    crate.registerComputation(computation_model)
UnboundLocalError: local variable 'computation_model' referenced before assignment
```

**Comment by mlev71** [comment]
Solved in release 0.1.7a2
Was caused by scoping issue in a try/except block
