### ISSUE TITLE
Unable to add software via add software option in fairscape cli 0.1.5

### ISSUE THREAD

**Issue by coleslaw481** [fairscape/fairscape-cli#7]
To reproduce, do the following in 0.1.5 of fairscape on python 3.8

```
mkdir foo
cd foo
# make a crate
fairscape-cli rocrate create --name 'a name' --organization-name 'org' --project-name 'some proj' `pwd`

# attempt to add software that only has a URL
fairscape-cli rocrate add software --name 'some tool' --description 'A tool to do something' --author 'bob smith' --version 0.1.0 --file-format .py --url https://github.com/someuser/somerepo `pwd`
```

The above outputs this error:

```
Traceback (most recent call last):
  File "/Users/churas/anaconda3/envs/python382/bin/fairscape-cli", line 8, in <module>
    sys.exit(cli())
  File "/Users/churas/anaconda3/envs/python382/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/churas/anaconda3/envs/python382/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/churas/anaconda3/envs/python382/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/churas/anaconda3/envs/python382/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/churas/anaconda3/envs/python382/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/churas/anaconda3/envs/python382/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/churas/anaconda3/envs/python382/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/churas/anaconda3/envs/python382/lib/python3.8/site-packages/fairscape_cli/rocrate/rocrate.py", line 189, in software
    source_path = pathlib.Path(source_filepath)
  File "/Users/churas/anaconda3/envs/python382/lib/python3.8/pathlib.py", line 1033, in __new__
    self = cls._from_parts(args, init=False)
  File "/Users/churas/anaconda3/envs/python382/lib/python3.8/pathlib.py", line 674, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/Users/churas/anaconda3/envs/python382/lib/python3.8/pathlib.py", line 658, in _parse_args
```

**Comment by mlev71** [comment]
Fixed with the build of 0.1.5a1
